services:
  postgres:
    image: postgres:15-alpine
    container_name: telemed_postgres
    environment:
      POSTGRES_DB: telemed
      POSTGRES_USER: telemed
      POSTGRES_PASSWORD: telemed123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d
    networks:
      - telemed_network

  redis:
    image: redis:7-alpine
    container_name: telemed_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - telemed_network

  # 開発用のWebサーバー（Nginx）
  nginx:
    image: nginx:alpine
    container_name: telemed_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - postgres
      - redis
    networks:
      - telemed_network

volumes:
  postgres_data:
  redis_data:

networks:
  telemed_network:
    driver: bridge
